const content = [
    {
        id: 1,
        title: 'Logo in Tshirt',
        body: 'Put Logo in the Tshirt for $$$$/month',
        image: 'illustration-flowing-conversation.svg',
    },
    {
        id: 2,
        title: 'Mention Sponsor',
        body: "Advertise sponsor in team social medias",
        image: 'illustration-flowing-conversation.svg',
    },
    {
        id: 3,
        title: 'Choose Team Color',
        body: "Choose team color for the year! ",
        image: 'illustration-flowing-conversation.svg',
    },
]

export default content


// var abi = /* abi generated by the compiler */
// var ZombieFeedingContract = web3.eth.contract(abi)
// var contractAddress = /* our contract address on Ethereum after deploying */
// var ZombieFeeding = ZombieFeedingContract.at(contractAddress)